TravelAgency/Models/Model1.cs
namespace TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Linq;

    public class Model1 : DbContext
    {
       
        public Model1()
            : base("name=Model1")
        {
        }

        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
    }

    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }


        public User()
        {
        }

        public User(string name, string surname, string login, string password)
        {
            Name = name;
            Surname = surname;
            Login = login;
            Password = password;
           

        }
    }

    public class Voyage
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Destination { get; set; }
        public int Days { get; set; }

        public Voyage()
        {
        }

        public Voyage(string destination, int days)
        {
            Destination = destination;
            Days = days;
        }
    }
}

TravelAgency/Controllers/BuyController.cs
using TravelAgency.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelAgency.Controllers
{
    public class BuyController : Controller
    {
        static Model1 model = new Model1();
        public ActionResult Index()
        {
           
            return View();
        }
        public ActionResult GetAddBasket(Voyage v)
        {
            ViewBag.voyageAdded = Session["Basket"];
            return View("Basket");
        }
        [HttpPost]
        public ActionResult AddBasket(int id)
        {

            ViewBag.id =id ;
            Voyage voyageAdded=model.Voyages.Find(id);
                   
                            if (Session["Basket"] == null)
                            {
                                Session["Basket"] = new List<Voyage>();                               
                            }
            var voyages = (List<Voyage>)Session["Basket"];
            voyages.Add(voyageAdded);
            Session["Basket"] = voyages;
            ViewBag.List = Session["Basket"];
            return View("Basket");
        
            
        }
        public ActionResult Basket()
        {
            ViewBag.voyageAdded = Session["Basket"];
            return View();
        }
        public ActionResult GetRemoveBasket(Voyage v)
        {
            return View("Remove");
        }
        public ActionResult RemoveBasket(Voyage v)
        {

            if (model.Voyages.Find(v.Id) != null)
            {
                model.Voyages.Remove(model.Voyages.Find(v.Id));
                model.SaveChanges();
                return View("Basket");
            }
            return View("Remove");
        }
    }
}


   

TravelAgency/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using TravelAgency.Models;

namespace TravelAgency.Controllers
{
    public class HomeController : Controller
    {

        static Model1 model = new Model1();
        // GET: Home
        public ActionResult Index()

        {
             /*           Voyage vo= new Voyage("China", 30);

                        model.Voyages.Add(vo);
                        model.SaveChanges();

            Voyage voo = new Voyage("Turkey", 7);
            model.Voyages.Add(voo);
            model.SaveChanges(); 

            Voyage vi = new Voyage("Argentina", 12);
            model.Voyages.Add(vi);
            model.SaveChanges();

            Voyage va = new Voyage("Nepal", 15);
            model.Voyages.Add(va);
            model.SaveChanges(); 

            Voyage vii = new Voyage("Australia", 30);
            model.Voyages.Add(vii);
            model.SaveChanges();

            Voyage vaa = new Voyage("Vietnam", 8);
            model.Voyages.Add(vaa);
            model.SaveChanges(); */

            return View();
        }

        [Authorize]
        public ActionResult GetPackages(Voyage v)
        {
         
            return View("Packages");
        }
        [Authorize]
        public ActionResult Packages()
        {
            ViewBag.voyages = model.Voyages.ToList();
            return View("Packages");
        }
/*        [HttpPost]
        public ActionResult Packages(Voyage v)
        {
            ViewBag.voygages = model.Voyages.ToList();
            return View("Packages", v);
     
        }*/

     
        public ActionResult List()
        {
            ViewBag.voygages = model.Voyages.ToList();
            return View();
        }

        public ActionResult Forum()
        {
            return View("Forum");
        }

        public ActionResult Testimonies()
        {
            return View("Testimonies");
        }

        public ActionResult Gallery()
        {
            return View("Gallery");
        }
        public ActionResult FAQ()
        {
            return View("FAQ");
        }
        public ActionResult Contact()
        {
            return View("Contact");
        }
    }
}

TravelAgency/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TravelAgency.Models;
namespace TravelAgency.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Connect()
        {
            var Authentifie = HttpContext.User.Identity.IsAuthenticated;
            ViewData["Authentifie"] = Authentifie;
            User user = null;
            if (Authentifie)
            {
                using (var db = new Model1())
                {
                    user = (from p in db.Users
                                where p.Login == HttpContext.User.Identity.Name
                                select p).FirstOrDefault();
                }
            }
            return View(user);
        }
        [HttpPost]
        public ActionResult Connect(User user, string returnUrl)
        {
            User perso = null;
            var Authentifie = HttpContext.User.Identity.IsAuthenticated;
            ViewData["Authentifie"] = Authentifie;
            if (ModelState.IsValid)
            {
                using (var db = new Model1())
                {
                    perso = (from p in db.Users
                             where p.Login.Equals(user.Login) && p.Password.Equals(user.Password)
                             select p).FirstOrDefault();
                    if (perso != null)
                    {
                        FormsAuthentication.SetAuthCookie(perso.Login.ToString(), false);
                        Authentifie = true;
                        //if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                        return Redirect("/Home/Packages");
                    }
                }
            }
            return View(user);
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                using (var db = new Model1())
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                }
                FormsAuthentication.SetAuthCookie(user.Login.ToString(), true);
                return Redirect("/Home/Packages");
            }
            return View(user);
        }



        public ActionResult Deconnexion()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

TravelAgency/Views/Buy/AddBasket.cshtml
@{
    ViewBag.Title = "AddBasket";
}

<h2>Item added successfully</h2>

TravelAgency/Views/Buy/Basket.cshtml
@{
    ViewBag.Title = "Basket";
}

<h2>Basket</h2>


<p>Here is your basket</p>

TravelAgency/Views/Buy/Remove.cshtml
@{
    ViewBag.Title = "GetAjouter";
}

<h2>Remove</h2>

TravelAgency/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align="center">Contact</h2>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</palign>

<h3>Alexis Voyage</h3>
<p>
    Address: <br>
    Room 340 <br>
    Nice Plaza<br>
    06000 Nice<br>
    France
</p>
<p>Tel: 0678946389</p>
<p>Email: alexis@alexisvoyage.com</p>
<p>Map</p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2885.983219743273!2d7.211593291104739!3d43.66931880875832!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12cdd11ade88ff4b%3A0xb05e6eac046fca6b!2simmeuble%20nice%20plaza!5e0!3m2!1sen!2sfr!4v1580130015919!5m2!1sen!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

TravelAgency/Views/Home/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align ="center">FAQ</h2>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</p>

<br>
<br>
<p><b>How much does it cost?</b></p>
<p>All depends on the trip. As we also offer custom-made voyages, please get in touch with one of our agents to discuss.</p>
<br>
<p><b>What is included?</b></p>
<p>We will be happy to help you with hotel, transport, tour guides and sightseeing. Pocket money however is not included.</p>
<br>
<p><b>How should I prepare for my trip?</b></p>
<p>Please make sure you have a valid passport (if travelling abroad). Otherwise, don't worry, we will take care of everything(including visas, health insurance etc.).</p>
<br>
<p><b>I need to cancel my trip because of medical reasons/personal circumstances. Can you offer a full refund?</b></p>
<p>This depends on the cause of cancellation. We can only offer up to 80% refund.</p>

TravelAgency/Views/Home/Forum.cshtml
@{
    ViewBag.Title = "Forum";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align ="center">Forum</h2>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</p>

TravelAgency/Views/Home/Gallery.cshtml
@{
    ViewBag.Title = "Gallery";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align ="center">Gallery</h2>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</p>

<br>
<br>
<br>

<div class="row" id="threeColumns">
    <div class="firstColumn">
        <p>
            Argentina
            <br>
            <img src="~/Images/Argentina_Gauchos.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Argentina_Patagonia.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Argentina_Tango.jpg" alt="Sample Image" width="80%" />
        </p>
        <br>
        <p>
            Australia
            <br>
            <img src="~/Images/Australia_Bridge.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Australia_GreatOceanRoad.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Australia_Kangaroo.jpg" alt="Sample Image" width="80%" />
        </p>
    </div>
    <br>
    <div class="secondColumn">
        <p>
            China
            <br>
            <img src="~/Images/China_Shanghai.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/China_Temple.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/ChinaGreatWall.jpg" alt="Sample Image" width="80%" />
        </p>
        <br>
        <p>
            Nepal
            <br>
            <img src="~/Images/Nepal_Bodhnath-Stupa.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Nepal_Kathmandu.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/NepalMonkeyTemple.jpg" alt="Sample Image" width="80%" />
        </p>
    </div>
    <br>
    <div class="thirdColumn">
        <p>
            Turkey
            <br>
            <img src="~/Images/Turkey_BlueMosque.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Turkey_HagiaSophia.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/TurkeyCappadocia.jpg" alt="Sample Image" width="80%" />
        </p>
        <br>
        <p>
            Vietnam
            <br>
            <img src="~/Images/Vietnam_HalongBay.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Vietnam_HoiAn.jpg" alt="Sample Image" width="80%" />
            <br>
            <img src="~/Images/Vietnam_Street.jpg" alt="Sample Image" width="80%" />
        </p>
    </div>
</div>

TravelAgency/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

 <img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right" >
<br>
<h1 align ="center">Alexis Voyage </h1>
<h3 align ="center">Travel with us</h3>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Connect", "Login") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</p>
<br>
<br>
<br>

<link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="../Images/China_Shanghai.jpg" alt="First slide" width="30%" height="30%">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="../Images/TurkeyCappadocia.jpg" alt="Second slide" width="30%" height="30%">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="../Images/Australia_Bridge.jpg" alt="Third slide" width="30%" height="30%">
            </div>
        </div>
    </div>
</div>


        @{ var imagePath = "";
            if (Request["photoChoice"] != null)
            {
                imagePath = @"../Images/" + Request["photoChoice"];
            }
        }

        <!DOCTYPE html>
        <html>
        <head>
            <title>Display Image on the Fly</title>
        </head>
        <body>
            <h1>Displaying an Image On the Fly</h1>
            <form method="post" action="">
                <div>
                    I want to see:
                    <select name="photoChoice">
                        <option value="ChinaGreatWall.jpg">Photo 1</option>
                        <option value="NepalMonkeyTemple.jpg">Photo 2</option>
                        <option value="TurkeyCappadocia.jpg">Photo 3</option>
                    </select>
                    &nbsp;
                    <input type="submit" value="Submit" />
                </div>
                <div style="padding:10px;">
                    @if (imagePath != "")
                    {
                        <img src="@imagePath" alt="Sample Image" width="300px" />

                    }
                </div>
            </form>
        </body>
    </html>

TravelAgency/Views/Home/Packages.cshtml
@{
    ViewBag.Title = "Packages";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align ="center">Packages</h2>

<p align="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
    @Html.ActionLink("Basket", "Basket", "Buy") &nbsp
</p>



<h1>Where would you like to go?</h1>
    <div>
        I want to go to                             :
        <select id="photoChoice" name="photoChoice">
            <option id="1" name ="country" value="1">China</option>
            <option id="2" name ="country" value="2">Turkey</option>
            <option id="3" name ="country" value="3">Argentina</option>
            <option id="4" name ="country" value="4">Nepal</option>
            <option id="5" name ="country" value="5">Australia</option>
            <option id="6" name ="country" value="6">Vietnam</option>
        </select>
        &nbsp;
        <input id ="submitCountry" type="submit" value="Submit" />
    </div>
    <div style="padding:10px;">

    </div>


<<script src="~/Scripts/jquery-3.4.1.js"></script>
 <script type="text/javascript">
     $("#submitCountry").click(function () {
         alert("bb");
         var url = "../../Buy/AddBasket";
         var content = $("#photoChoice").val();
         alert(content);
         $.post(url, { id: content }, function () { alert("sent")});
         alert("done");

     });
 </script>

<h2>Trips</h2>

@foreach (TravelAgency.Models.Voyage item in ViewBag.voyages)
{
    <p>@item.Id @item.Destination @item.Days days</p>
}

TravelAgency/Views/Home/Testimonies.cshtml
@{
    ViewBag.Title = "Testimonies";
}

<img id="logo" src="../Images/TravelAgencyLogo.jpg" alt="Logo" width="15%" align="center" float="right">
<h2 align ="center">Testimonies</h2>

<p align ="center">
    @Html.ActionLink("Homepage", "Index") &nbsp
    @Html.ActionLink("Packages", "Packages") &nbsp
    @Html.ActionLink("Forum", "Forum") &nbsp
    @Html.ActionLink("Testimonies", "Testimonies") &nbsp
    @Html.ActionLink("Gallery", "Gallery") &nbsp
    @Html.ActionLink("FAQ", "FAQ") &nbsp
    @Html.ActionLink("Contact", "Contact") &nbsp
</p>

<br>
<br>
<p class="box">
    I really enjoyed my trip to China! The organisation of the trip and the tour guides were outstanding.
    <div style='text-align:center;'><div>~John</div></div>
</p>
<br>

<p class="box">
    It had been our greatest dream to go to Australia. We can confidently say that we had the time of our lives. All that thanks to Alexis Voyage.
    <div style='text-align:center;'><div>~Kristy</div></div>
</p>
<br>

<p class="box">
    It was my first trip in Asia. Thanks to Alexis Voyage, I discovered the rich Eastern culture and overcame my fear of unknown. Thank you!
    <div style='text-align:center;'><div>~Maddy</div></div>
</p>
<br>

<p class="box">
    We went to Turkey on our honeymoon. Alexis Voyage took care of our hotel, transport and sightseeing.
    Our custom-made trip was a truly unforgettable experience that we will remember for the rest of our lives!
    <div style='text-align:center;'><div>~Josh</div></div>
</p>

TravelAgency/Views/Login/Connect.cshtml
@Model Users.Models.User
@{
    bool test = (bool)@ViewData["Authentifie"];
}
@if (test)
{
    <h3> Utilisateur deja connecte avec le login @Model.Login </h3>
    @Html.ActionLink("Cliquerpourvousdeconnecter?", "Deconnexion")
}
else
{
    <h3>Connexion :</h3>
    using (Html.BeginForm())
    {
        <div>
            @Html.Label("Login")
            <br />
            @Html.TextBox("Login")
            <br />
            @Html.ValidationMessage("Login")
        </div>
        <div>
            @Html.Label("Password")
            <br />
            @Html.Password("Password")
            <br />
            @Html.ValidationMessage("Password")
        </div>
        <input type="submit" value="Connexion" />
        <br />
        @Html.ActionLink("Register", "Register")
    }
}
@if (Model != null && test == false)
{
    <span>Authentification error</span>
}

TravelAgency/Views/Login/Register.cshtml
@{
    ViewBag.Title = "Inscription";
}

<h2>Inscription</h2>

@Model Users.Models.User
<h3>Inscription </h3>
@using (Html.BeginForm())
{
    <div>
        @Html.Label("login")
        @Html.TextBox("login")
        @Html.ValidationMessage("login")
    </div>
    <div>
        @Html.Label("Password")
        @Html.Password("Password")
        @Html.ValidationMessage("Password")
    </div>
    <input type="submit" value="Register" />
}

TravelAgency/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>